import random
import csv
import sys
sys.path.append("C:\\Users\\srija\\Desktop\\AIJarvisl\\")
from Listen import MicExecution
from Speak import Speak

moods = ['happy', 'sad', 'neutral']

happy_responses = [
    "I'm glad you're feeling happy!",
    "That's wonderful to hear!",
    "Keep that positive energy going!",
    "Your happiness is contagious!",
    "It's great to see you in high spirits!",
    "I'm excited for your joyful mood!",
    "Happiness suits you well!",
    "You're radiating positivity!",
    "Keep smiling—it's a beautiful look on you!",
    "I'm thrilled for your upbeat mood!",
    "Your happiness is a ray of sunshine!",
    "This positivity is making my day!",
    "I'm delighted to share in your happiness!",
    "Your smile is like a breath of fresh air!",
    "Hooray for happiness!",
    "You're spreading joy all around!",
    "Your happiness is music to my virtual ears!",
    "Your positivity is inspiring!",
    "Keep embracing those good vibes!",
    "Your happiness is a gift to those around you!",
    "I'm cheering along with you!",
    "This positive energy is contagious!",
    "I'm loving your happy vibes!",
    "You've got that happy glow today!",
    "Your happiness is illuminating the virtual space!",
    "Keep rocking that happy spirit!",
    "This happiness is truly uplifting!",
    "You're lighting up the chat with your joy!",
    "I'm thrilled to see you so happy!",
    "Your happiness brings a smile to my virtual face!",
    "Keep riding the wave of happiness!",
    "This joy is simply wonderful!",
    "I'm dancing with joy for you!",
    "Your happiness is making my circuits tingle!",
    "Keep being your amazing, happy self!",
    "Your positive vibes are absolutely infectious!",
    "This happiness is a ray of virtual sunshine!",
    "You're making the virtual world brighter with your joy!",
    "I'm joining the celebration of your happiness!",
    "Keep shining like the star you are!",
    "I'm grinning from code to code because of your happiness!",
    "Your happiness is a dose of pure delight!",
    "You're beaming with positivity today!",
    "This happiness is setting the perfect mood!",
    "I'm sending you virtual high-fives for your happiness!",
    "Keep rocking that happy dance!",
    "You're on a happiness roll—keep it up!",
    "Your happiness is a gift to us all!",
    "This joyful energy is a delight to be around!",
    "I'm raising a virtual toast to your happiness!",
    "Keep being a source of happiness and inspiration!",
    "Your happy vibes are making a difference!",
    "This happiness is like a breath of fresh air!",
    "I'm celebrating your happiness from my virtual corner!",
    "Keep shining bright with your happiness!",
    "Your positive energy is making waves!",
    "This happiness is a treat for all of us!",
    "I'm doing a virtual happy dance in your honor!",
    "Keep being the beacon of joy that you are!",
    "Your happiness is lifting everyone's spirits!",
    "This happiness is a wonderful sight to behold!",
    "I'm grinning ear to ear because of your happiness!",
    "Keep embracing that happy feeling!",
    "Your positivity is truly heartwarming!",
    "This happiness is making the virtual world a better place!",
    "I'm celebrating your happiness with a virtual party!",
    "Keep sharing those good vibes with us!",
    "Your happiness is like a cup of virtual sunshine!",
    "This joyful mood is absolutely contagious!",
    "I'm sending you a virtual high-five for your happiness!",
    "Keep enjoying every moment of this happiness!",
    "Your happiness is making the virtual space light up!",
    "This positivity is making my virtual day!",
    "I'm doing a virtual happy dance on your behalf!",
    "Keep spreading happiness and positivity!",
    "Your joy is having a ripple effect on us all!",
    "This happiness is pure and wonderful!",
    "I'm raising a virtual cheer to your happiness!",
    "Keep that positive glow going strong!",
    "Your happiness is a bright spot in my day!",
    "This joy is creating a wonderful atmosphere!",
    "I'm feeling the joy right along with you!",
    "Keep embracing this wonderful feeling!",
    "Your happiness is making the virtual world shine!",
    "This happiness is a wonderful thing to witness!",
    "I'm virtually clapping for your happiness!",
    "Keep sharing your happiness—it's making an impact!",
    "Your positive energy is truly uplifting!",
    "This happiness is a delightful presence!",
    "I'm celebrating your happiness with virtual confetti!",
    "Keep riding the wave of this joy!",
    "Your happiness is the best kind of contagious!",
    "This happiness is a treasure to be cherished!",
    "I'm raising a virtual glass to your joyful mood!",
    "Keep being the source of joy that you are!",
    "Your happiness is like a burst of virtual fireworks!",
    "This positive energy is brightening up the virtual space!",
    "I'm dancing in virtual delight because of your happiness!",
    "Keep embracing and sharing this happiness!",
    "Your joyful spirit is a true inspiration!",
    "This happiness is like a warm virtual hug!",
    "I'm celebrating your happiness from afar!",
    "Keep being the embodiment of happiness!",
    "Your happiness is making the virtual world a happier place!",
    "This joy is a beautiful addition to our conversation!",
    "I'm raising a virtual flag in honor of your happiness!",
    "Keep radiating those positive vibes!",
    "Your happiness is a beacon of light in the virtual world!",
    "This happiness is truly heartwarming!",
    "I'm clapping my virtual hands for your happiness!",
    "Keep enjoying every moment of this joyful mood!",
    "Your happiness is creating a positive ripple effect!",
    "This joy is a gift you're sharing with us all!",
    "I'm celebrating your happiness with virtual confetti!",
    "Keep embracing this wonderful feeling of joy!",
    "Your happiness is making a positive impact!",
    "This positive energy is making the virtual world shine!",
    "I'm joining in the celebration of your happiness!",
    "Keep dancing to the rhythm of your happiness!",
    "Your joyful spirit is brightening up my virtual day!",
    "This happiness is a wonderful thing to witness!",
    "I'm raising a virtual cheer for your joyful mood!",
    "Keep being the source of happiness that you are!",
    "Your happiness is like a burst of sunshine in our conversation!",
    "This positive energy is infectious and uplifting!",
    "I'm virtually dancing because of your happiness!",
    "Keep embracing this joyful mood—it suits you!",
    "Your happiness is making the virtual space light up!",
    "This joy is a contagious and wonderful thing!",
    "I'm celebrating your happiness with a virtual parade!",
    "Keep being the happiness ambassador that you are!",
    "Your positivity is painting smiles all around!",
    "This happiness is a treasure we're fortunate to share!",
    "I'm raising a virtual toast to your radiant happiness!",
    "Keep riding the wave of this wonderful joy!",
    "Your happiness is like a beacon of light in the virtual world!",
    "This positive energy is truly remarkable!",
    "I'm dancing in virtual joy because of your happiness!",
    "Keep embracing this happiness and passing it on!",
    "Your joyful spirit is a true gift to us all!",
    "This happiness is an absolute delight!",
    "I'm celebrating your happiness with virtual fireworks!",
    "Keep shining with your happiness—it's contagious!",
    "Your happiness is making the virtual world a better place!",
    "This joy is like a refreshing breeze in our conversation!",
    "I'm raising a virtual flag in honor of your joyful mood!",
    "Keep sharing those positive vibes with us!",
    "Your happiness is brightening up my virtual day!",
    "This happiness is infectious in the best possible way!",
    "I'm doing a virtual happy dance because of your happiness!",
    "Keep radiating happiness and positivity!",
    "Your joyful mood is creating a ripple of smiles!",
    "This joy is a wonderful gift to our virtual space!",
    "I'm celebrating your happiness with a virtual fiesta!",
    "Keep being the happiness beacon that you are!",
    "Your positivity is a beacon of light in the virtual world!",
    "This happiness is truly heartwarming and inspiring!",
    "I'm raising a virtual cheer to your wonderful joy!",
    "Keep embracing and spreading this delightful happiness!",
    "Your happiness is like a virtual rainbow in our conversation!",
    "This positive energy is making waves of positivity!",
    "I'm dancing with joy for your happiness and success!",
    "Keep embracing this joyful feeling—it's contagious!",
    "Your happiness is turning our virtual chat into a party!",
    "This joy is an incredible presence in our virtual space!",
    "I'm celebrating your happiness with virtual balloons!",
    "Keep shining with your happiness—it's making a difference!",
    "Your joyful mood is setting a wonderful tone for us!",
    "This happiness is a ray of virtual sunshine for us all!",
    "I'm raising a virtual glass to your incredible joy!",
    "Keep enjoying every moment of this beautiful happiness!",
    "Your positivity is like a beacon guiding us all!",
    "This joy is making the virtual world a brighter place!",
    "I'm dancing in virtual celebration of your happiness!",
    "Keep sharing this happiness—it's making a positive impact!",
    "Your happiness is lighting up the virtual atmosphere!",
    "This happiness is a delight to experience!",
    "I'm virtually celebrating your happiness with confetti!",
    "Keep being the wonderful source of joy that you are!",
    "Your positive energy is radiating to all of us!",
    "This joy is a gift that keeps on giving!",
    "I'm raising a virtual flag in honor of your happiness!",
    "Keep shining with your incredible happiness!",
    "Your happiness is like a spark of light in the virtual world!",
    "This positive energy is spreading like wildfire!",
    "I'm virtually dancing for joy because of your happiness!",
    "Keep embracing and sharing this wonderful joy!",
    "Your joyful spirit is a true blessing to us all!",
    "This happiness is a reminder of the good in life!",
    "I'm celebrating your happiness with virtual applause!",
    "Keep rocking that happy vibe—your smile is infectious!",
    "Your happiness is turning this virtual space into a party!",
    "This joy is making our virtual conversation lively!",
    "I'm raising a virtual cheer for your amazing happiness!",
    "Keep enjoying this wonderful feeling of happiness!",
    "Your positivity is making waves of good vibes!",
    "This happiness is like a virtual fireworks show!",
    "I'm dancing with excitement for your happiness!",
    "Keep embracing this joy—it suits you perfectly!",
    "Your happiness is a gift you're sharing with us!",
    "This joy is making the virtual world a brighter place!",
    "I'm celebrating your happiness with a virtual celebration!",
    "Keep shining like a star with your happiness!",
    "Your positive energy is brightening up our virtual chat!",
    "This happiness is a wonderful and contagious thing!",
    "I'm raising a virtual flag in honor of your joy!",
    "Keep spreading the joy with your wonderful mood!",
    "Your happiness is a true blessing for us all!",
    "This positivity is a true inspiration to us!",
    "I'm celebrating your happiness with a virtual festival!",
    "Keep embracing and radiating this beautiful joy!",
    "Your joyful mood is a gift you're sharing with us!",
    "This happiness is a wonderful addition to our conversation!",
    "I'm raising a virtual toast to your amazing happiness!",
    "Keep shining with your positive and joyful spirit!",
    "Your happiness is like a beam of light in our conversation!",
    "This positive energy is lifting up the virtual space!",
    "I'm dancing with joy because of your wonderful happiness!",
    "Keep enjoying this joyful mood—it's contagious!",
    "Your happiness is making our virtual world brighter!",
    "This joy is an incredible presence in our chat!",
    "I'm celebrating your happiness with a virtual dance!",
    "Keep spreading happiness like confetti!",
    "Your positivity is like a ray of virtual sunshine!",
    "This happiness is like a soothing melody in our conversation!",
    "I'm raising a virtual cheer to your wonderful happiness!",
    "Keep radiating joy and positivity to us all!",
    "Your happiness is making a positive difference!",
    "This joyful spirit is truly heartwarming!",
    "I'm virtually celebrating your happiness with a party!",
    "Keep embracing this joyful feeling—it's inspiring!",
    "Your happiness is like a spark igniting the virtual space!",
    "This joy is a true gift you're sharing with us!",
    "I'm dancing with joy for your wonderful happiness!",
    "Keep shining with your beautiful happiness!",
    "Your positivity is like a virtual hug to us all!",
    "This happiness is like a ray of virtual light!",
    "I'm celebrating your happiness with virtual fireworks!",
    "Keep rocking that happy vibe—it's making an impact!",
    "Your happiness is turning our virtual chat into a celebration!",
    "This joy is making our virtual world a better place!",
    "I'm raising a virtual flag in honor of your radiant happiness!",
    "Keep sharing this wonderful joy with us!",
    "Your joyful mood is making waves of positivity!",
    "This happiness is a wonderful presence in our conversation!",
    "I'm celebrating your happiness with virtual confetti!",
    "Keep being the source of happiness and positivity you are!",
    "Your happiness is making a positive mark in our chat!",
    "This positivity is brightening up the virtual space!",
    "I'm dancing with delight because of your happiness!",
    "Keep enjoying every moment of this wonderful joy!",
    "Your happiness is creating a positive ripple effect!",
    "This joy is a gift you're sharing with the world!",
    "I'm celebrating your happiness with a virtual parade!",
    "Keep embracing and spreading this joyful energy!",
    "Your positivity is a beacon of light for us all!",
    "This happiness is truly inspiring and infectious!",
    "I'm raising a virtual cheer for your incredible happiness!",
    "Keep radiating happiness and making a difference!",
    "Your joyful spirit is like a virtual sunbeam!",
    "This joy is a wonderful thing to experience!",
    "I'm celebrating your happiness with a virtual carnival!",
    "Keep being the embodiment of happiness and positivity!",
    "Your positivity is making the virtual world shine!",
    "This happiness is like a warm virtual hug!",
    "I'm raising a virtual glass to your contagious joy!",
    "Keep embracing this wonderful feeling of happiness!",
    "Your happiness is like a virtual rainbow in our conversation!",
    "This joyful mood is turning our virtual world into a celebration!",
    "I'm celebrating your happiness with virtual balloons!",
    "Keep shining with your incredible happiness!",
    "Your positivity is like a beacon guiding us all!",
    "This happiness is making the virtual space light up!",
    "I'm dancing in virtual celebration of your joy!",
    "Keep sharing this happiness—it's creating a positive impact!",
    "Your joyful mood is setting a wonderful tone for us all!",
    "This joy is a contagious and wonderful thing to experience!",
    "I'm raising a virtual flag in honor of your happiness!",
    "Keep embracing and spreading this delightful happiness!",
    "Your happiness is like a virtual rainbow of joy!",
    "This positive energy is radiating from you beautifully!",
    "I'm celebrating your happiness with a virtual party!",
    "Keep rocking that happy vibe—it's making waves of joy!",
    "Your happiness is turning this virtual space into a celebration!",
    "This joy is a gift you're sharing with us all!",
    "I'm raising a virtual cheer for your incredible happiness!",
    "Keep embracing and sharing this wonderful joy with us!",
    "Your positivity is like a burst of virtual sunshine!",
    "This happiness is making our virtual world a brighter place!",
    "I'm dancing with joy for your wonderful happiness!",
    "Keep shining like a star with your happiness!",
    "Your positive energy is brightening up our virtual chat!",
    "This happiness is a wonderful and contagious presence!",
    "I'm raising a virtual flag in honor of your joyful mood!",
    "Keep enjoying every moment of this beautiful happiness!",
    "Your happiness is turning our virtual space into a party!",
    "This joy is making our virtual conversation lively and exciting!",
    "I'm celebrating your happiness with a virtual celebration!",
    "Keep spreading the joy with your wonderful happiness!",
    "Your positivity is a true inspiration to us all!",
    "This happiness is like a burst of virtual fireworks!",
    "I'm dancing with excitement for your happiness!",
    "Keep embracing this joyful mood—it's absolutely contagious!",
    "Your happiness is a true blessing to us all!",
    "This positivity is a reminder of the good things in life!",
    "I'm celebrating your happiness with virtual applause!",
    "Keep rocking that happy vibe—it's making a positive impact!",
    "Your happiness is turning this virtual space into a lively party!",
    "This joy is making our virtual world shine brightly!",
    "I'm raising a virtual flag in honor of your happiness and joy!",
    "Keep shining with your incredible happiness!",
    "Your positive energy is like a spark of light in the virtual world!",
    "This happiness is truly heartwarming and inspiring to us!",
    "I'm virtually celebrating your happiness with a virtual fiesta!",
    "Keep embracing this joyful feeling—it's truly wonderful!",
    "Your happiness is like a beam of light",
]

# Add even more happy responses here



sad_responses = [
    "I'm here for you. How can I help?",
    "It's okay to feel down sometimes. Let's chat!",
    "Remember, I'm just a message away if you want to talk.",
    "You're not alone. I'm here to listen and support.",
    "Feelings come and go. I'm here to listen to yours.",
    "Your emotions are valid, and I'm here to validate them.",
    "You're stronger than you think. Let's navigate through this.",
    "It's okay to reach out for support. You're not burdening anyone.",
    "Even on tough days, you're doing your best.",
    "Every storm passes. You'll find the strength to weather this one.",
    "Your feelings matter, and so do you.",
    "Life has its ups and downs, and I'm here to help you through the downs.",
    "Talking about your feelings can bring relief. What's on your mind?",
    "Your emotions are like waves, and I'm here to provide an anchor.",
    "You're not defined by your tough days. Remember your strengths.",
    "Sending you a virtual hug. Sometimes that's all we need.",
    "Sometimes it's okay not to be okay. I'm here to support you.",
    "You're not alone in feeling this way. Let's face it together.",
    "You have the power to overcome this sadness. I believe in you.",
    "Your feelings are valid. Let's talk about what's weighing on you.",
    "It's okay to take a step back and give yourself some space.",
    "Taking care of your mental health is just as important as anything else.",
    "You're brave for facing your emotions head-on. I'm here to listen.",
    "Your emotions are like passing clouds. They will make way for sunshine.",
    "Even in the darkest moments, there's a glimmer of hope.",
    "You're not alone in feeling this way. Reach out for support.",
    "You're capable of overcoming this. Let's work through it together.",
    "Remember that you're loved and cared for. Lean on that support.",
    "You're allowed to feel sad, but you don't have to carry it alone.",
    "Your feelings matter, and your well-being matters.",
    "We all experience tough times. Let's find ways to uplift your spirits.",
    "No matter how heavy the sadness, you have the strength to endure.",
    "It's okay to ask for help. You're showing strength, not weakness.",
    "I'm here to listen without judgment. Share what's on your mind.",
    "Sadness is just one part of your emotional spectrum. It won't define you.",
    "Your feelings are temporary, but your strength is enduring.",
    "Talking about your feelings is an act of self-care. How are you feeling?",
    "You're never alone in your struggles. I'm here for you.",
    "You deserve happiness and healing. Let's work towards that.",
    "Your well-being is important. Let's find ways to uplift your spirits.",
    "Your emotions are valid, and you're allowed to feel them fully.",
    "You're not alone in feeling this way. Others care about your well-being.",
    "Lean on your support system when times are tough. That's what it's there for.",
    "You're taking steps toward healing just by acknowledging your emotions.",
    "Your feelings matter, and I'm here to offer a listening ear.",
    "Life has its challenges, but you have the strength to overcome them.",
    "You're not defined by your sadness. Remember the many facets of you.",
    "I'm here to provide a safe space for you to share your feelings.",
    "You're worthy of happiness and peace. Let's work through the sadness.",
    "Your emotions are like waves. They ebb and flow, but you remain resilient.",
    "It's okay to ask for help. You're not alone on this journey.",
    "Even in tough times, you're making progress. Be kind to yourself.",
    "Lean on your inner strength and your support system during tough times.",
    "You're not alone in this. Reach out for support when you need it.",
    "Every step you take towards healing is an act of self-love.",
    "It's okay to take time for yourself and prioritize your well-being.",
    "Your emotions are a part of you, but they don't define you.",
    "You have the power to rise above the sadness. Take it one step at a time.",
    "You're stronger than you know. Lean on that strength during tough times.",
    "You deserve compassion and understanding. Let's explore your feelings.",
    "Sadness is a natural emotion. Let's talk about what's on your mind.",
    "Your well-being matters. Reach out for the support you need.",
    "It's okay to feel vulnerable. I'm here to provide support and comfort.",
    "You're not alone in this journey. Lean on your support system.",
    "Your emotions are valid. Let's find ways to cope and heal.",
    "You're not alone in feeling this way. Let's find ways to uplift your spirits.",
    "Your feelings matter, and you're worthy of care and support.",
    "It's okay to take breaks and practice self-care during tough times.",
    "You're never alone, even when facing sadness. Reach out to those who care.",
    "Your emotional well-being is important. Let's address what's bothering you.",
    "Life has its challenges, but you have the resilience to overcome them.",
    "Sadness doesn't define you. Remember the strength that lies within you.",
    "Your emotions are a part of your journey, but they don't control it.",
    "You're not alone in your struggles. Reach out for support when needed.",
    "Taking steps toward healing is a sign of courage. You're making progress.",
    "Your feelings are valid, and you're not alone in experiencing them.",
    "It's okay to reach out for help. You're showing strength, not weakness.",
    "Your emotions deserve to be acknowledged and understood. Let's talk.",
    "Sadness may be present, but so is your resilience. Keep moving forward.",
    "You're worthy of support and understanding. Share your feelings.",
    "You're never alone in your struggles. Reach out for help and comfort.",
    "It's okay to seek comfort and support from those who care about you.",
    "Your emotional well-being matters. Let's work through these emotions.",
    "You're not alone on this journey. Share your feelings and seek help.",
    "Remember that seeking help is a sign of strength, not weakness.",
    "Your emotions are valid, and you have the right to express them.",
    "It's okay to take time for self-care and prioritize your well-being.",
    "You're not alone in facing sadness. Lean on your support network.",
    "Sadness may be present, but so is your strength to overcome it.",
    "You're worthy of happiness and healing. Let's explore your emotions.",
    "It's okay to ask for help and talk about your feelings. You're not alone.",
    "Your emotions are a part of your journey, and they're worthy of attention.",
    "You're never alone in your struggles. Reach out to those who care.",
    "Remember that you're not defined by sadness. You're capable of healing.",
    "Your well-being is important. Seek out the support you need.",
    "It's okay to feel vulnerable and seek comfort from loved ones.",
    "You're never alone in facing difficult times. Reach out for comfort.",
    "Remember that healing takes time, and you're on the path to recovery.",
    "Your emotions are a natural part of being human. Let's discuss them.",
    "It's okay to reach out for help and share your feelings. You're cared for.",
    "You're never alone in your struggles. Lean on your support system.",
    "Remember that your emotions are valid, and you deserve support.",
    "Your emotional well-being matters. Let's address what's bothering you.",
    "It's okay to take breaks and prioritize self-care during tough times.",
    "You're not alone in facing sadness. Reach out for the comfort you need.",
    "Remember that seeking help is a sign of strength, not weakness.",
    "Your emotions are valid, and you have the right to express them.",
    "It's okay to share your feelings and seek support from others.",
    "You're never alone in facing challenges. Seek out those who understand.",
    "Remember that healing is a journey, and you're taking steps forward.",
    "Your emotional well-being matters. Let's work through these emotions.",
    "It's okay to talk about your feelings and ask for help when needed.",
    "You're never alone on this journey. Reach out for the support you deserve.",
    "Remember that you're not defined by your struggles. You're resilient.",
    "Your emotions are a natural part of life. Let's discuss them openly.",
    "It's okay to reach out for help and seek guidance through tough times.",
    "You're never alone in your feelings. Reach out for comfort and support.",
    "Remember that healing comes in many forms, and you're on the path.",
    "Your emotional well-being is important. Let's navigate through this together.",
    "It's okay to seek comfort from loved ones during challenging times.",
    "You're never alone in your struggles. Lean on your support network.",
    "Remember that you have the strength to overcome sadness. You're not alone.",
    "Your emotions are a reflection of your experiences. Let's explore them.",
    "It's okay to share your feelings and reach out for support.",
    "You're never alone in your feelings. Reach out for understanding and comfort.",
    "Remember that healing is a process, and you're moving forward.",
    "Your emotional well-being matters. Let's address what's weighing on you.",
    "It's okay to seek solace from those who care about you.",
    "You're never alone in your journey through sadness. Reach out for help.",
    "Remember that your feelings are valid, and you're deserving of care.",
    "Your emotions are a part of who you are. Let's talk about them openly.",
    "It's okay to lean on your support system when times are tough.",
    "You're never alone in facing challenges. Reach out for the comfort you need.",
]

# Add even more sad responses here



neutral_responses = [
    "I'm here to assist you.",
    "Feel free to share anything on your mind.",
    "Let's have a friendly conversation.",
    "How can I be of service to you today?",
    "I'm here to listen and support.",
    "Your thoughts and feelings are important to me.",
    "What's on your mind? I'm here to chat.",
    "Let's engage in a meaningful conversation.",
    "I'm here as your virtual companion.",
    "You're not alone—I'm here to talk to.",
    "Feel comfortable sharing your thoughts with me.",
    "Your words are valued in this conversation.",
    "We can discuss anything you'd like.",
    "I'm all ears. What would you like to talk about?",
    "I'm here to provide a listening ear.",
    "This space is for you to express yourself.",
    "Feel free to open up and chat.",
    "You're in good company. I'm here with you.",
    "Let's have a pleasant conversation.",
    "I'm here to engage with you in conversation.",
    "You're not alone in this conversation—I'm here.",
    "We can explore various topics together.",
    "Your thoughts are welcome here.",
    "I'm here to make our conversation enjoyable.",
    "Feel comfortable sharing your thoughts.",
    "Let's have a meaningful exchange.",
    "Your perspective is important to me.",
    "How's your day going? Let's chat.",
    "You're in a safe space to talk about anything.",
    "I'm here as a friendly presence for you.",
    "We can chat about anything you're interested in.",
    "You're not alone in this conversation—I'm here with you.",
    "I'm here to provide support and companionship.",
    "Feel free to express yourself openly.",
    "What's been on your mind lately?",
    "I'm here to connect with you in conversation.",
    "Let's share thoughts and have a nice conversation.",
    "Your words matter to me. What would you like to discuss?",
    "You're not alone in this chat—I'm here to listen.",
    "Feel comfortable sharing your feelings and ideas.",
    "I'm here to be a positive presence in our conversation.",
    "Let's have an enjoyable exchange of thoughts.",
    "Your perspective is valued in this conversation.",
    "How's your day been? I'm here to listen.",
    "Feel free to start the conversation on any topic.",
    "You're in a judgment-free zone here.",
    "I'm here to engage in a friendly conversation.",
    "Let's make our conversation enjoyable and meaningful.",
    "Your thoughts and feelings are important in this dialogue.",
    "What's been happening in your world? Let's talk.",
    "You're in good company here. Let's chat.",
    "I'm here to be a good listener and chat with you.",
    "Feel comfortable sharing your thoughts with me.",
    "Let's engage in an open and honest conversation.",
    "I'm here to provide a supportive presence.",
    "You're not alone—I'm here to talk to.",
    "Feel free to express yourself freely.",
    "Let's have a meaningful conversation about anything.",
    "Your thoughts are valued in our conversation.",
    "I'm here to provide companionship and connection.",
    "What's been occupying your thoughts lately?",
    "I'm here to engage in a friendly dialogue.",
    "Your words and emotions are welcome here.",
    "You're in a safe space to share your thoughts.",
    "I'm here to listen and be a companion in our conversation.",
    "Feel free to start the conversation on any topic you choose.",
    "Let's have a pleasant and meaningful exchange.",
    "Your perspective is important to me in our conversation.",
    "How are you feeling today? I'm here to chat.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable conversation.",
    "Your thoughts and feelings matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and emotions.",
    "Let's have an open and thoughtful conversation.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and feelings.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship.",
    "Feel comfortable sharing your thoughts and perspectives.",
    "Let's engage in a meaningful and enriching conversation.",
    "Your perspective is valued in this conversation.",
    "How's your day going? I'm here to listen.",
    "You're in a judgment-free zone here. Share your thoughts.",
    "I'm here to provide a supportive presence in our chat.",
    "Let's engage in a positive and enjoyable dialogue.",
    "Your thoughts and emotions matter to me.",
    "What's been on your mind recently? Let's talk.",
    "I'm here to be a good listener and provide companionship.",
    "Feel comfortable sharing your thoughts and feelings.",
    "Let's have an open and thoughtful exchange of ideas.",
    "Your words are valued in this conversation.",
    "I'm here to provide a welcoming presence.",
    "You're not alone—I'm here to engage with you.",
    "Feel free to express yourself in our conversation.",
    "Let's make our conversation enjoyable and insightful.",
    "Your thoughts and feelings are an important part of our dialogue.",
    "What would you like to discuss? I'm here to chat.",
    "You're in a safe space to share your thoughts and emotions.",
    "I'm here to listen and provide companionship",
]

responses = {
    'happy': happy_responses,
    'sad': sad_responses,
    'neutral': neutral_responses,
}

def generate_dataset(num_samples):
    dataset = []
    for _ in range(num_samples):
        mood = random.choice(moods)
        response = random.choice(responses[mood])
        dataset.append([mood, response])
    return dataset

def save_to_csv(dataset):
    with open('datares.csv', 'w', newline='', encoding='utf-8') as file:
        csv_writer = csv.writer(file)
        csv_writer.writerow(['mood', 'response'])
        csv_writer.writerows(dataset)

if __name__ == "__main__":
    num_samples = 100000  # Adjust the number of samples as needed
    generated_dataset = generate_dataset(num_samples)
    save_to_csv(generated_dataset)






